"""Generated from protocol.toml. Do not edit manually."""

PROTOCOL_VERSION = "0.2.0"

TERMINAL_REGRESSION_PASS = "regression_pass"
TERMINAL_EXPLICIT_ESCALATION = "explicit_escalation"
TERMINAL_UNSUPPORTED = "unsupported"
TERMINAL_UNKNOWN = "unknown"
TERMINAL_APPROVAL_PENDING = "approval_pending"

ERR_OK = 0
ERR_INVALID_REQUEST = 100
ERR_SCHEMA_MISMATCH = 101
ERR_UNSUPPORTED_BOUNDARY = 102
ERR_UNKNOWN_DEVICE_IDENTITY = 103
ERR_TOPOLOGY_MISMATCH = 104
ERR_APPROVAL_REQUIRED = 105
ERR_SAFETY_REFUSED = 106
ERR_TRANSPORT_ERROR = 200
ERR_DEVICE_TIMEOUT = 201
ERR_INTERNAL_ERROR = 500

MSG_DEVICE_STATUS_REQUEST = 1
MSG_DEVICE_STATUS_RESPONSE = 32769
MSG_TOPOLOGY_VALIDATE_REQUEST = 2
MSG_TOPOLOGY_VALIDATE_RESPONSE = 32770
MSG_RUN_START_REQUEST = 3
MSG_RUN_START_RESPONSE = 32771
MSG_FLASH_REQUEST = 16
MSG_FLASH_RESPONSE = 32784
MSG_CAPTURE_START_REQUEST = 32
MSG_CAPTURE_START_RESPONSE = 32800
MSG_MOCK_CONFIG_REQUEST = 48
MSG_MOCK_CONFIG_RESPONSE = 32816
MSG_DIAGNOSE_REQUEST = 64
MSG_DIAGNOSE_RESPONSE = 32832
MSG_APPROVAL_REQUIRED = 240
MSG_ERROR_RESPONSE = 33023

STATE_CHANGING_ACTIONS = frozenset([
    "flash",
    "reset",
    "drive_pin",
    "mock_start",
    "mock_stop",
    "firmware_update",
    "bitstream_update",
])

GOLDEN_UPGRADE_MODE_DEFAULT = "disabled"
