/* Generated from protocol.toml. Do not edit manually. */
#ifndef AP_PROTOCOL_GENERATED_H
#define AP_PROTOCOL_GENERATED_H

#define AP_PROTOCOL_VERSION "0.2.0"

typedef enum ap_err {
    AP_ERR_OK = 0,
    AP_ERR_INVALID_REQUEST = 100,
    AP_ERR_SCHEMA_MISMATCH = 101,
    AP_ERR_UNSUPPORTED_BOUNDARY = 102,
    AP_ERR_UNKNOWN_DEVICE_IDENTITY = 103,
    AP_ERR_TOPOLOGY_MISMATCH = 104,
    AP_ERR_APPROVAL_REQUIRED = 105,
    AP_ERR_SAFETY_REFUSED = 106,
    AP_ERR_TRANSPORT_ERROR = 200,
    AP_ERR_DEVICE_TIMEOUT = 201,
    AP_ERR_INTERNAL_ERROR = 500,
} ap_err_t;

typedef enum ap_msg {
    AP_MSG_DEVICE_STATUS_REQUEST = 0x0001,
    AP_MSG_DEVICE_STATUS_RESPONSE = 0x8001,
    AP_MSG_TOPOLOGY_VALIDATE_REQUEST = 0x0002,
    AP_MSG_TOPOLOGY_VALIDATE_RESPONSE = 0x8002,
    AP_MSG_RUN_START_REQUEST = 0x0003,
    AP_MSG_RUN_START_RESPONSE = 0x8003,
    AP_MSG_FLASH_REQUEST = 0x0010,
    AP_MSG_FLASH_RESPONSE = 0x8010,
    AP_MSG_CAPTURE_START_REQUEST = 0x0020,
    AP_MSG_CAPTURE_START_RESPONSE = 0x8020,
    AP_MSG_MOCK_CONFIG_REQUEST = 0x0030,
    AP_MSG_MOCK_CONFIG_RESPONSE = 0x8030,
    AP_MSG_DIAGNOSE_REQUEST = 0x0040,
    AP_MSG_DIAGNOSE_RESPONSE = 0x8040,
    AP_MSG_APPROVAL_REQUIRED = 0x00F0,
    AP_MSG_ERROR_RESPONSE = 0x80FF,
} ap_msg_t;

#endif