#ifndef AP_SHARED_H
#define AP_SHARED_H

#define AP_PROTOCOL_VERSION "0.2.0"

typedef enum ap_err {
    AP_OK = 0,
    AP_ERR_INVALID_REQUEST = 100,
    AP_ERR_SCHEMA_MISMATCH = 101,
    AP_ERR_UNSUPPORTED_BOUNDARY = 102,
    AP_ERR_UNKNOWN_DEVICE_IDENTITY = 103,
    AP_ERR_TOPOLOGY_MISMATCH = 104,
    AP_ERR_APPROVAL_REQUIRED = 105,
    AP_ERR_SAFETY_REFUSED = 106,
    AP_ERR_TRANSPORT = 200,
    AP_ERR_DEVICE_TIMEOUT = 201,
    AP_ERR_INTERNAL = 500,
} ap_err_t;

#endif
